token: my_secret
commands:
  test:
    description: my pretty command
    response: my lovely response
    url: https://google.com
    headers:
      - name: X-Forwarded-For
        value: somevalue
    arguments:
      - name: arg1
        type: string
        description: argument 1
        required: true
      - name: arg2
        type: int
        description: argument 2
        required: false
    data: 
      user: "{{ .arg1 }}"
      id: "{{ .arg2 }}"
  short_test:
    description: my pretty short command
    response: my quick lovely response
    url: https://github.com
    method: GET
  outer:
    description: Outer command
    subcommand-group:
      middle:
        description: Inner command group
        subcommand:
          inner:
            description: Most nested command possible
            response: Nested subcommand!
            url: https://youtube.com
            headers:
              - name: X-Forwarded-For
                value: somevalue
            arguments:
              - name: arg1
                type: string
                description: argument 1
                required: true
              - name: arg2
                type: int
                description: argument 2
                required: false
            data: 
              user: "{{ .arg1 }}"
              id: "{{ .arg2 }}"
    subcommand:
      inner2:
        description: Command nested one level deep
        response: Single nested subcommand!
        url: https://gmail.com
        headers:
          - name: X-Forwarded-For
            value: somevalue
        arguments:
          - name: arg1
            type: string
            description: argument 1
            required: true
          - name: arg2
            type: int
            description: argument 2
            required: false
        data: 
          user: "{{ .arg1 }}"
          id: "{{ .arg2 }}"






